#!/usr/bin/env python3
"""Generate the field-driven WDL from spec.py.

Run with NO arguments to regenerate every covered file in place:

    python wdl/codegen/generate.py

Other modes:
    python wdl/codegen/generate.py --check    # exit 1 if any file is stale (ignores header timestamp)
    python wdl/codegen/generate.py --print <name>   # print one file to stdout (debug)

Whole files generated (struct + constructors; 100% field-driven):
    sequencing_run.wdl, sample.wdl, patient.wdl, patient.update_samples.wdl

Marker blocks filled in hand-written files (between `# CODEGEN:BEGIN id` / `# CODEGEN:END id`):
    patient.define.wdl, patient.out.wdl
"""

import os
import re
import sys
from datetime import datetime

import spec

I = "    "
WDL_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))  # .../wdl
SCRIPT_REL = "wdl/codegen/generate.py"
SPEC_REL = "wdl/codegen/spec.py"


# --------------------------------------------------------------------- helpers

def is_optional(t):
    return t.endswith("?")


def strip_opt(t):
    return t[:-1] if is_optional(t) else t


def is_array(elem):
    return elem.startswith("Array[")


def optionalize(t):
    return t if is_optional(t) else t + "?"


def header(target_name):
    ts = datetime.now().strftime("%Y:%m:%d:%H:%M:%S")
    return "\n".join([
        "# +-------------------------------------------------------------------------+",
        "# | THIS FILE IS GENERATED BY CODE - DO NOT EDIT.                           |",
        f"# | Generated by {SCRIPT_REL} from {SPEC_REL}".ljust(73) + " |",
        f"# | Generated at {ts}".ljust(73) + " |",
        f"# | To regenerate: python {SCRIPT_REL}".ljust(73) + " |",
        "# +-------------------------------------------------------------------------+",
    ])


HEADER_RE = re.compile(r"^# \+-+\+\n(?:^# \|.*\n)+^# \+-+\+\n", re.MULTILINE)


def strip_header(text):
    """Remove the generated banner so --check ignores the volatile timestamp."""
    return HEADER_RE.sub("", text)


# --------------------------------------------------------------------- emitters

def emit_struct(struct_name):
    fields = spec.STRUCTS[struct_name]
    width = max(len(f.wdl_type) for f in fields)
    lines = [f"struct {struct_name} {{"]
    for f in fields:
        line = f"{I}{f.wdl_type:<{width}} {f.name}"
        if f.origin:
            pad = " " * max(2, 60 - len(line))
            line = f"{line}{pad}# {f.origin}"
        lines.append(line)
    lines.append("}")
    return "\n".join(lines)


def emit_update_record(struct_name, record_var, out_name):
    """Per-record Update workflow: every field is an optional overlay input."""
    fields = spec.STRUCTS[struct_name]
    out = [f"workflow Update{struct_name} {{", f"{I}input {{", f"{I}{I}{struct_name} {record_var}"]
    for f in fields:
        out.append(f"{I}{I}{optionalize(f.wdl_type)} {f.name}")
    out.append(f"{I}}}\n")
    out.append(f"{I}{struct_name} updated = object {{")
    body = []
    for f in fields:
        if is_optional(f.wdl_type):
            rhs = f"if defined({f.name}) then {f.name} else {record_var}.{f.name}"
        else:
            rhs = f"select_first([{f.name}, {record_var}.{f.name}])"
        body.append(f"{I}{I}{f.name}: {rhs}")
    out.append(",\n".join(body))
    out.append(f"{I}}}\n")
    out.append(f"{I}output {{")
    out.append(f"{I}{I}{struct_name} {out_name} = updated")
    out.append(f"{I}}}")
    out.append("}")
    return "\n".join(out)


def emit_update_samples():
    over = [f for f in spec.SAMPLE if f.overlaid]
    out = ["workflow UpdateSamples {", f"{I}input {{", f"{I}{I}Patient patient"]
    for f in over:
        out.append(f"{I}{I}Array[{strip_opt(f.wdl_type)}]? {f.name}")
    out.append(f"{I}}}\n")

    out.append(f"{I}# Build each updated Sample in a single pass. Each provided overlay array carries")
    out.append(f"{I}# one entry per sample (aligned by index); an absent or empty array leaves the")
    out.append(f"{I}# field unchanged. INVARIANT: any provided overlay array has length == length(patient.samples).")
    for f in over:
        default = "[[]]" if is_array(strip_opt(f.wdl_type)) else "[]"
        out.append(f"{I}Array[{strip_opt(f.wdl_type)}] {f.name}_arr = select_first([{f.name}, {default}])")
    out.append("")

    out.append(f"{I}scatter (i in range(length(patient.samples))) {{")
    out.append(f"{I}{I}Sample sample_i = patient.samples[i]")
    out.append(f"{I}{I}Sample updated_sample_i = object {{")
    body = []
    for f in spec.SAMPLE:
        if f.overlaid:
            length = (f"length(flatten({f.name}_arr))" if is_array(strip_opt(f.wdl_type))
                      else f"length({f.name}_arr)")
            body.append(f"{I}{I}{I}{f.name}: if {length} > 0 then {f.name}_arr[i] else sample_i.{f.name}")
        else:
            body.append(f"{I}{I}{I}{f.name}: sample_i.{f.name}")
    out.append(",\n".join(body))
    out.append(f"{I}{I}}}")
    out.append(f"{I}}}")
    out.append(f"{I}Array[Sample] samples = updated_sample_i\n")

    out.append(TUMOR_NORMAL_SELECTION)

    out.append(f"{I}# Only the sample sets change here; every other patient field is carried over.")
    out.append(f"{I}Patient updated_patient_obj = object {{")
    pbody = []
    for f in spec.PATIENT:
        if f.name == "normal_samples":
            rhs = "select_first([normal_samples, patient.normal_samples])"
        elif f.name == "matched_normal_sample":
            rhs = "if defined(matched_normal_sample) then matched_normal_sample else patient.matched_normal_sample"
        elif f.name in spec.PATIENT_COMPUTED:
            rhs = f.name
        else:
            rhs = f"patient.{f.name}"
        pbody.append(f"{I}{I}{f.name}: {rhs}")
    out.append(",\n".join(pbody))
    out.append(f"{I}}}\n")
    out.append(f"{I}output {{")
    out.append(f"{I}{I}Patient updated_patient = updated_patient_obj")
    out.append(f"{I}}}")
    out.append("}")
    return "\n".join(out)


TUMOR_NORMAL_SELECTION = """\
    scatter (tumor_sample in patient.tumor_samples) {
        scatter (sample in samples) {
            if (sample.name == tumor_sample.name) {
                Sample selected_tumor_sample = sample
            }
        }
        Sample tumor_samples = select_all(selected_tumor_sample)[0]
    }

    if (patient.has_normal) {
        scatter (normal_sample in patient.normal_samples) {
            scatter (sample in samples) {
                if (sample.name == normal_sample.name) {
                    Sample selected_normal_sample = sample
                }
            }
            Sample normal_samples = select_all(selected_normal_sample)[0]
        }
        if (defined(patient.matched_normal_sample)) {
            Sample previous_matched_normal_sample = select_first([patient.matched_normal_sample])
            scatter (sample in normal_samples) {
                if (sample.name == previous_matched_normal_sample.name) {
                    Sample matched_normal_samples = sample
                }
            }
            Sample matched_normal_sample = select_all(matched_normal_samples)[0]
        }
    }
"""


# patient.out.wdl maps Patient -> flat workflow outputs. Run-scope fields live on
# SequencingRun and are gathered as Array[Array[File]]; sample-scope fields are the
# Sample overlay fields (minus sequencing_runs); shard-scope fields get a _scattered
# suffix. A few public output names/types are fixed by the existing contract:
OUT_RUN_FIELDS = ["callable_loci", "total_read_counts",
                  "denoised_total_copy_ratios", "snppanel_allelic_pileup_summaries"]
OUT_TYPE_OVERRIDE = {"annotated_somatic_variants_idx": "Array[File?]?"}


def emit_output():
    sample_out = [f for f in spec.SAMPLE if f.overlaid and f.name != "sequencing_runs"]
    shard_out = [f for f in spec.SHARD if f.overlaid]
    L = []
    w = L.append

    w("workflow Output {")
    w(f"{I}input {{")
    w(f"{I}{I}Patient patient")
    w(f"{I}}}\n")

    w(f"{I}scatter (sample in patient.samples) {{")
    w(f"{I}{I}scatter (seqrun in sample.sequencing_runs) {{")
    for rf in OUT_RUN_FIELDS:
        w(f"{I}{I}{I}File? run_{rf} = seqrun.{rf}")
    w(f"{I}{I}}}")
    for rf in OUT_RUN_FIELDS:
        w(f"{I}{I}Array[File] out_{rf} = select_all(run_{rf})")
    w(f"{I}{I}String sample_name = sample.name")
    for f in sample_out:
        w(f"{I}{I}{f.wdl_type} out_{f.name} = sample.{f.name}")
    w(f"{I}}}\n")

    for rf in OUT_RUN_FIELDS:
        w(f"{I}if (length(flatten(out_{rf})) > 0) {{")
        w(f"{I}{I}Array[Array[File]] {rf}_out = out_{rf}")
        w(f"{I}}}")
    w("")
    for f in sample_out:
        w(f"{I}if (length(select_all(out_{f.name})) > 0) {{")
        w(f"{I}{I}Array[{strip_opt(f.wdl_type)}] {f.name}_out = select_all(out_{f.name})")
        w(f"{I}}}")
    w("")
    w(f"{I}scatter (shard in patient.shards) {{")
    for f in shard_out:
        w(f"{I}{I}File? shard_{f.name} = shard.{f.name}")
    w(f"{I}}}")
    for f in shard_out:
        w(f"{I}if (length(select_all(shard_{f.name})) > 0) {{")
        w(f"{I}{I}Array[File] {f.name}_out = select_all(shard_{f.name})")
        w(f"{I}}}")
    w("")
    w(f"{I}output {{")
    for rf in OUT_RUN_FIELDS:
        w(f"{I}{I}Array[Array[File]]? {rf} = {rf}_out")
    w(f"{I}{I}Array[String]? sample_names_ordered = sample_name")
    for f in sample_out:
        otype = OUT_TYPE_OVERRIDE.get(f.name, f"Array[{strip_opt(f.wdl_type)}]?")
        w(f"{I}{I}{otype} {f.name} = {f.name}_out")
    for f in shard_out:
        w(f"{I}{I}Array[File]? {f.name}_scattered = {f.name}_out")
    w(f"{I}}}")
    w("}")
    return "\n".join(L)


# --------------------------------------------------------------------- files

def file_sequencing_run():
    return "\n\n".join([
        "version development",
        header("sequencing_run.wdl"),
        emit_struct("SequencingRun"),
        emit_update_record("SequencingRun", "sequencing_run", "updated_sequencing_run"),
    ]) + "\n"


def file_sample():
    return "\n\n".join([
        "version development",
        header("sample.wdl"),
        'import "sequencing_run.wdl" as seqrun',
        emit_struct("Sample"),
        emit_update_record("Sample", "sample", "updated_sample"),
    ]) + "\n"


def file_patient():
    return "\n\n".join([
        "version development",
        header("patient.wdl"),
        'import "sample.wdl" as s\nimport "shard.wdl" as sh',
        emit_struct("Patient"),
        emit_update_record("Patient", "patient", "updated_patient"),
    ]) + "\n"


def file_shard():
    return "\n\n".join([
        "version development",
        header("shard.wdl"),
        emit_struct("Shard"),
        emit_update_record("Shard", "shard", "updated_shard"),
    ]) + "\n"


def file_update_samples():
    return "\n\n".join([
        "version development",
        header("patient.update_samples.wdl"),
        'import "sample.wdl" as s\nimport "patient.wdl" as p',
        emit_update_samples(),
    ]) + "\n"


def file_patient_out():
    return "\n\n".join([
        "version development",
        header("patient.out.wdl"),
        'import "patient.wdl" as p',
        emit_output(),
    ]) + "\n"


WHOLE_FILES = {
    "sequencing_run.wdl": file_sequencing_run,
    "sample.wdl": file_sample,
    "shard.wdl": file_shard,
    "patient.wdl": file_patient,
    "patient.update_samples.wdl": file_update_samples,
    "patient.out.wdl": file_patient_out,
}


# --------------------------------------------------------------------- main

def write_all():
    for name, builder in WHOLE_FILES.items():
        path = os.path.join(WDL_DIR, name)
        with open(path, "w") as fh:
            fh.write(builder())
        print(f"wrote {name}")


def check_all():
    stale = []
    for name, builder in WHOLE_FILES.items():
        path = os.path.join(WDL_DIR, name)
        on_disk = open(path).read() if os.path.exists(path) else ""
        if strip_header(on_disk).strip() != strip_header(builder()).strip():
            stale.append(name)
    if stale:
        print("STALE (run generate.py): " + ", ".join(stale))
        return 1
    print("all generated files up to date")
    return 0


if __name__ == "__main__":
    args = sys.argv[1:]
    if not args:
        write_all()
    elif args[0] == "--check":
        sys.exit(check_all())
    elif args[0] == "--print" and len(args) > 1:
        print(WHOLE_FILES[args[1]]())
    else:
        sys.exit(f"usage: generate.py [--check | --print <file>]")
