version: 1.2
workflows:
  - name: MultiSampleSomaticWorkflow
    subclass: WDL
    publish: true
    primaryDescriptorPath: /wdl/multi-sample_somatic_workflow.wdl
    authors:
      - orcid: 0000-0001-9584-9135
      - name: Philipp Hähnel

  - name: CreateMutect2PanelOfNormals
    subclass: WDL
    publish: true
    primaryDescriptorPath: /wdl/resources/create_mutect2_pon.wdl
    authors:
      - orcid: 0000-0001-9584-9135
      - name: Philipp Hähnel

  - name: CreateReadCountPanelOfNormals
    subclass: WDL
    publish: true
    primaryDescriptorPath: /wdl/resources/create_read_count_pon.wdl
    authors:
      - orcid: 0000-0001-9584-9135
      - name: Philipp Hähnel

  - name: CreateAFonlyVCF
    subclass: WDL
    publish: true
    primaryDescriptorPath: /wdl/resources/create_AF_only_germline_resource.wdl
    authors:
      - orcid: 0000-0001-9584-9135
      - name: Philipp Hähnel

  - name: CreateAFonlyVCFfromFile
    subclass: WDL
    publish: true
    primaryDescriptorPath: /wdl/resources/create_AF_only_germline_resource_from_file.wdl
    authors:
      - orcid: 0000-0001-9584-9135
      - name: Philipp Hähnel

  - name: CollectAllelicCounts
    subclass: WDL
    publish: true
    primaryDescriptorPath: /wdl/collect_allelic_counts.wdl
    authors:
      - orcid: 0000-0001-9584-9135
      - name: Philipp Hähnel

  - name: SelectPileupSummaries
    subclass: WDL
    publish: true
    primaryDescriptorPath: /wdl/select_pileups.wdl
    authors:
      - orcid: 0000-0001-9584-9135
      - name: Philipp Hähnel

  - name: CalculateContamination
    subclass: WDL
    publish: true
    primaryDescriptorPath: /wdl/calculate_contamination.wdl
    authors:
      - orcid: 0000-0001-9584-9135
      - name: Philipp Hähnel

  - name: CollectReadCounts
    subclass: WDL
    publish: true
    primaryDescriptorPath: /wdl/collect_read_counts.wdl
    authors:
      - orcid: 0000-0001-9584-9135
      - name: Philipp Hähnel

  - name: CollectCoveredRegions
    subclass: WDL
    publish: true
    primaryDescriptorPath: /wdl/collect_covered_regions.wdl
    authors:
      - orcid: 0000-0001-9584-9135
      - name: Philipp Hähnel

  - name: Absolute
    subclass: WDL
    publish: true
    primaryDescriptorPath: /wdl/absolute.wdl
    authors:
      - orcid: 0000-0001-9584-9135
      - name: Philipp Hähnel

  - name: AbsoluteExtractSolution
    subclass: WDL
    publish: true
    primaryDescriptorPath: /wdl/absolute_extract.wdl
    authors:
      - orcid: 0000-0001-9584-9135
      - name: Philipp Hähnel

  - name: AbsoluteExtractSolution_Patient
    subclass: WDL
    publish: true
    primaryDescriptorPath: /wdl/absolute_extract.patient.wdl
    authors:
      - orcid: 0000-0001-9584-9135
      - name: Philipp Hähnel
