version development

# +-------------------------------------------------------------------------+
# | THIS FILE IS GENERATED BY CODE - DO NOT EDIT.                           |
# | Generated by wdl/codegen/generate.py from wdl/codegen/spec.py           |
# | To regenerate: python wdl/codegen/generate.py                           |
# +-------------------------------------------------------------------------+

import "patient.wdl" as p

workflow Output {
    input {
        Patient patient
    }

    scatter (sample in patient.samples) {
        scatter (seqrun in sample.sequencing_runs) {
            File? run_callable_loci = seqrun.callable_loci
            File? run_total_read_counts = seqrun.total_read_counts
            File? run_denoised_total_copy_ratios = seqrun.denoised_total_copy_ratios
            File? run_snppanel_allelic_pileup_summaries = seqrun.snppanel_allelic_pileup_summaries
        }
        Array[File] out_callable_loci = select_all(run_callable_loci)
        Array[File] out_total_read_counts = select_all(run_total_read_counts)
        Array[File] out_denoised_total_copy_ratios = select_all(run_denoised_total_copy_ratios)
        Array[File] out_snppanel_allelic_pileup_summaries = select_all(run_snppanel_allelic_pileup_summaries)
        String sample_name = sample.name
        File? out_harmonized_callable_loci = sample.harmonized_callable_loci
        File? out_harmonized_denoised_total_copy_ratios = sample.harmonized_denoised_total_copy_ratios
        File? out_harmonized_snppanel_allelic_pileup_summaries = sample.harmonized_snppanel_allelic_pileup_summaries
        File? out_contamination_table = sample.contamination_table
        File? out_af_segmentation_table = sample.af_segmentation_table
        File? out_allelic_pileup_summaries = sample.allelic_pileup_summaries
        File? out_aggregated_allelic_read_counts = sample.aggregated_allelic_read_counts
        Float? out_genotype_error_probabilities = sample.genotype_error_probabilities
        File? out_af_model_parameters = sample.af_model_parameters
        File? out_cr_model_parameters = sample.cr_model_parameters
        File? out_called_copy_ratio_segmentation = sample.called_copy_ratio_segmentation
        File? out_cr_plot = sample.cr_plot
        File? out_acs_copy_ratio_segmentation = sample.acs_copy_ratio_segmentation
        Float? out_acs_copy_ratio_skew = sample.acs_copy_ratio_skew
        File? out_annotated_somatic_variants = sample.annotated_somatic_variants
        File? out_annotated_somatic_variants_idx = sample.annotated_somatic_variants_idx
        File? out_absolute_snv_maf = sample.absolute_snv_maf
        File? out_absolute_indel_maf = sample.absolute_indel_maf
        File? out_absolute_acr_rdata = sample.absolute_acr_rdata
        File? out_absolute_acr_plot = sample.absolute_acr_plot
        Int? out_absolute_acr_solution = sample.absolute_acr_solution
        File? out_absolute_acr_maf = sample.absolute_acr_maf
        File? out_absolute_acr_segtab = sample.absolute_acr_segtab
        File? out_absolute_acr_segtab_igv = sample.absolute_acr_segtab_igv
        File? out_absolute_acr_table = sample.absolute_acr_table
        Float? out_absolute_acr_purity = sample.absolute_acr_purity
        Float? out_absolute_acr_ploidy = sample.absolute_acr_ploidy
        File? out_absolute_tcr_rdata = sample.absolute_tcr_rdata
        File? out_absolute_tcr_plot = sample.absolute_tcr_plot
        Int? out_absolute_tcr_solution = sample.absolute_tcr_solution
        File? out_absolute_tcr_maf = sample.absolute_tcr_maf
        File? out_absolute_tcr_segtab = sample.absolute_tcr_segtab
        File? out_absolute_tcr_segtab_igv = sample.absolute_tcr_segtab_igv
        File? out_absolute_tcr_table = sample.absolute_tcr_table
        Float? out_absolute_tcr_purity = sample.absolute_tcr_purity
        Float? out_absolute_tcr_ploidy = sample.absolute_tcr_ploidy
        Int? out_timepoint = sample.timepoint
        Float? out_user_purity = sample.user_purity
        Float? out_user_ploidy = sample.user_ploidy
    }

    if (length(flatten(out_callable_loci)) > 0) {
        Array[Array[File]] callable_loci_out = out_callable_loci
    }
    if (length(flatten(out_total_read_counts)) > 0) {
        Array[Array[File]] total_read_counts_out = out_total_read_counts
    }
    if (length(flatten(out_denoised_total_copy_ratios)) > 0) {
        Array[Array[File]] denoised_total_copy_ratios_out = out_denoised_total_copy_ratios
    }
    if (length(flatten(out_snppanel_allelic_pileup_summaries)) > 0) {
        Array[Array[File]] snppanel_allelic_pileup_summaries_out = out_snppanel_allelic_pileup_summaries
    }

    if (length(select_all(out_harmonized_callable_loci)) > 0) {
        Array[File] harmonized_callable_loci_out = select_all(out_harmonized_callable_loci)
    }
    if (length(select_all(out_harmonized_denoised_total_copy_ratios)) > 0) {
        Array[File] harmonized_denoised_total_copy_ratios_out = select_all(out_harmonized_denoised_total_copy_ratios)
    }
    if (length(select_all(out_harmonized_snppanel_allelic_pileup_summaries)) > 0) {
        Array[File] harmonized_snppanel_allelic_pileup_summaries_out = select_all(out_harmonized_snppanel_allelic_pileup_summaries)
    }
    if (length(select_all(out_contamination_table)) > 0) {
        Array[File] contamination_table_out = select_all(out_contamination_table)
    }
    if (length(select_all(out_af_segmentation_table)) > 0) {
        Array[File] af_segmentation_table_out = select_all(out_af_segmentation_table)
    }
    if (length(select_all(out_allelic_pileup_summaries)) > 0) {
        Array[File] allelic_pileup_summaries_out = select_all(out_allelic_pileup_summaries)
    }
    if (length(select_all(out_aggregated_allelic_read_counts)) > 0) {
        Array[File] aggregated_allelic_read_counts_out = select_all(out_aggregated_allelic_read_counts)
    }
    if (length(select_all(out_genotype_error_probabilities)) > 0) {
        Array[Float] genotype_error_probabilities_out = select_all(out_genotype_error_probabilities)
    }
    if (length(select_all(out_af_model_parameters)) > 0) {
        Array[File] af_model_parameters_out = select_all(out_af_model_parameters)
    }
    if (length(select_all(out_cr_model_parameters)) > 0) {
        Array[File] cr_model_parameters_out = select_all(out_cr_model_parameters)
    }
    if (length(select_all(out_called_copy_ratio_segmentation)) > 0) {
        Array[File] called_copy_ratio_segmentation_out = select_all(out_called_copy_ratio_segmentation)
    }
    if (length(select_all(out_cr_plot)) > 0) {
        Array[File] cr_plot_out = select_all(out_cr_plot)
    }
    if (length(select_all(out_acs_copy_ratio_segmentation)) > 0) {
        Array[File] acs_copy_ratio_segmentation_out = select_all(out_acs_copy_ratio_segmentation)
    }
    if (length(select_all(out_acs_copy_ratio_skew)) > 0) {
        Array[Float] acs_copy_ratio_skew_out = select_all(out_acs_copy_ratio_skew)
    }
    if (length(select_all(out_annotated_somatic_variants)) > 0) {
        Array[File] annotated_somatic_variants_out = select_all(out_annotated_somatic_variants)
    }
    if (length(select_all(out_annotated_somatic_variants_idx)) > 0) {
        Array[File] annotated_somatic_variants_idx_out = select_all(out_annotated_somatic_variants_idx)
    }
    if (length(select_all(out_absolute_snv_maf)) > 0) {
        Array[File] absolute_snv_maf_out = select_all(out_absolute_snv_maf)
    }
    if (length(select_all(out_absolute_indel_maf)) > 0) {
        Array[File] absolute_indel_maf_out = select_all(out_absolute_indel_maf)
    }
    if (length(select_all(out_absolute_acr_rdata)) > 0) {
        Array[File] absolute_acr_rdata_out = select_all(out_absolute_acr_rdata)
    }
    if (length(select_all(out_absolute_acr_plot)) > 0) {
        Array[File] absolute_acr_plot_out = select_all(out_absolute_acr_plot)
    }
    if (length(select_all(out_absolute_acr_solution)) > 0) {
        Array[Int] absolute_acr_solution_out = select_all(out_absolute_acr_solution)
    }
    if (length(select_all(out_absolute_acr_maf)) > 0) {
        Array[File] absolute_acr_maf_out = select_all(out_absolute_acr_maf)
    }
    if (length(select_all(out_absolute_acr_segtab)) > 0) {
        Array[File] absolute_acr_segtab_out = select_all(out_absolute_acr_segtab)
    }
    if (length(select_all(out_absolute_acr_segtab_igv)) > 0) {
        Array[File] absolute_acr_segtab_igv_out = select_all(out_absolute_acr_segtab_igv)
    }
    if (length(select_all(out_absolute_acr_table)) > 0) {
        Array[File] absolute_acr_table_out = select_all(out_absolute_acr_table)
    }
    if (length(select_all(out_absolute_acr_purity)) > 0) {
        Array[Float] absolute_acr_purity_out = select_all(out_absolute_acr_purity)
    }
    if (length(select_all(out_absolute_acr_ploidy)) > 0) {
        Array[Float] absolute_acr_ploidy_out = select_all(out_absolute_acr_ploidy)
    }
    if (length(select_all(out_absolute_tcr_rdata)) > 0) {
        Array[File] absolute_tcr_rdata_out = select_all(out_absolute_tcr_rdata)
    }
    if (length(select_all(out_absolute_tcr_plot)) > 0) {
        Array[File] absolute_tcr_plot_out = select_all(out_absolute_tcr_plot)
    }
    if (length(select_all(out_absolute_tcr_solution)) > 0) {
        Array[Int] absolute_tcr_solution_out = select_all(out_absolute_tcr_solution)
    }
    if (length(select_all(out_absolute_tcr_maf)) > 0) {
        Array[File] absolute_tcr_maf_out = select_all(out_absolute_tcr_maf)
    }
    if (length(select_all(out_absolute_tcr_segtab)) > 0) {
        Array[File] absolute_tcr_segtab_out = select_all(out_absolute_tcr_segtab)
    }
    if (length(select_all(out_absolute_tcr_segtab_igv)) > 0) {
        Array[File] absolute_tcr_segtab_igv_out = select_all(out_absolute_tcr_segtab_igv)
    }
    if (length(select_all(out_absolute_tcr_table)) > 0) {
        Array[File] absolute_tcr_table_out = select_all(out_absolute_tcr_table)
    }
    if (length(select_all(out_absolute_tcr_purity)) > 0) {
        Array[Float] absolute_tcr_purity_out = select_all(out_absolute_tcr_purity)
    }
    if (length(select_all(out_absolute_tcr_ploidy)) > 0) {
        Array[Float] absolute_tcr_ploidy_out = select_all(out_absolute_tcr_ploidy)
    }
    if (length(select_all(out_timepoint)) > 0) {
        Array[Int] timepoint_out = select_all(out_timepoint)
    }
    if (length(select_all(out_user_purity)) > 0) {
        Array[Float] user_purity_out = select_all(out_user_purity)
    }
    if (length(select_all(out_user_ploidy)) > 0) {
        Array[Float] user_ploidy_out = select_all(out_user_ploidy)
    }

    scatter (shard in patient.shards) {
        File? shard_raw_calls_mutect2_vcf = shard.raw_calls_mutect2_vcf
        File? shard_raw_calls_mutect2_vcf_idx = shard.raw_calls_mutect2_vcf_idx
        File? shard_raw_mutect2_stats = shard.raw_mutect2_stats
        File? shard_raw_mutect2_bam_out = shard.raw_mutect2_bam_out
        File? shard_raw_mutect2_bai_out = shard.raw_mutect2_bai_out
        File? shard_raw_mutect2_artifact_priors = shard.raw_mutect2_artifact_priors
    }
    if (length(select_all(shard_raw_calls_mutect2_vcf)) > 0) {
        Array[File] raw_calls_mutect2_vcf_out = select_all(shard_raw_calls_mutect2_vcf)
    }
    if (length(select_all(shard_raw_calls_mutect2_vcf_idx)) > 0) {
        Array[File] raw_calls_mutect2_vcf_idx_out = select_all(shard_raw_calls_mutect2_vcf_idx)
    }
    if (length(select_all(shard_raw_mutect2_stats)) > 0) {
        Array[File] raw_mutect2_stats_out = select_all(shard_raw_mutect2_stats)
    }
    if (length(select_all(shard_raw_mutect2_bam_out)) > 0) {
        Array[File] raw_mutect2_bam_out_out = select_all(shard_raw_mutect2_bam_out)
    }
    if (length(select_all(shard_raw_mutect2_bai_out)) > 0) {
        Array[File] raw_mutect2_bai_out_out = select_all(shard_raw_mutect2_bai_out)
    }
    if (length(select_all(shard_raw_mutect2_artifact_priors)) > 0) {
        Array[File] raw_mutect2_artifact_priors_out = select_all(shard_raw_mutect2_artifact_priors)
    }

    output {
        Array[Array[File]]? callable_loci = callable_loci_out
        Array[Array[File]]? total_read_counts = total_read_counts_out
        Array[Array[File]]? denoised_total_copy_ratios = denoised_total_copy_ratios_out
        Array[Array[File]]? snppanel_allelic_pileup_summaries = snppanel_allelic_pileup_summaries_out
        Array[String]? sample_names_ordered = sample_name
        Array[File]? harmonized_callable_loci = harmonized_callable_loci_out
        Array[File]? harmonized_denoised_total_copy_ratios = harmonized_denoised_total_copy_ratios_out
        Array[File]? harmonized_snppanel_allelic_pileup_summaries = harmonized_snppanel_allelic_pileup_summaries_out
        Array[File]? contamination_table = contamination_table_out
        Array[File]? af_segmentation_table = af_segmentation_table_out
        Array[File]? allelic_pileup_summaries = allelic_pileup_summaries_out
        Array[File]? aggregated_allelic_read_counts = aggregated_allelic_read_counts_out
        Array[Float]? genotype_error_probabilities = genotype_error_probabilities_out
        Array[File]? af_model_parameters = af_model_parameters_out
        Array[File]? cr_model_parameters = cr_model_parameters_out
        Array[File]? called_copy_ratio_segmentation = called_copy_ratio_segmentation_out
        Array[File]? cr_plot = cr_plot_out
        Array[File]? acs_copy_ratio_segmentation = acs_copy_ratio_segmentation_out
        Array[Float]? acs_copy_ratio_skew = acs_copy_ratio_skew_out
        Array[File]? annotated_somatic_variants = annotated_somatic_variants_out
        Array[File?]? annotated_somatic_variants_idx = annotated_somatic_variants_idx_out
        Array[File]? absolute_snv_maf = absolute_snv_maf_out
        Array[File]? absolute_indel_maf = absolute_indel_maf_out
        Array[File]? absolute_acr_rdata = absolute_acr_rdata_out
        Array[File]? absolute_acr_plot = absolute_acr_plot_out
        Array[Int]? absolute_acr_solution = absolute_acr_solution_out
        Array[File]? absolute_acr_maf = absolute_acr_maf_out
        Array[File]? absolute_acr_segtab = absolute_acr_segtab_out
        Array[File]? absolute_acr_segtab_igv = absolute_acr_segtab_igv_out
        Array[File]? absolute_acr_table = absolute_acr_table_out
        Array[Float]? absolute_acr_purity = absolute_acr_purity_out
        Array[Float]? absolute_acr_ploidy = absolute_acr_ploidy_out
        Array[File]? absolute_tcr_rdata = absolute_tcr_rdata_out
        Array[File]? absolute_tcr_plot = absolute_tcr_plot_out
        Array[Int]? absolute_tcr_solution = absolute_tcr_solution_out
        Array[File]? absolute_tcr_maf = absolute_tcr_maf_out
        Array[File]? absolute_tcr_segtab = absolute_tcr_segtab_out
        Array[File]? absolute_tcr_segtab_igv = absolute_tcr_segtab_igv_out
        Array[File]? absolute_tcr_table = absolute_tcr_table_out
        Array[Float]? absolute_tcr_purity = absolute_tcr_purity_out
        Array[Float]? absolute_tcr_ploidy = absolute_tcr_ploidy_out
        Array[Int]? timepoint = timepoint_out
        Array[Float]? user_purity = user_purity_out
        Array[Float]? user_ploidy = user_ploidy_out
        Array[File]? raw_calls_mutect2_vcf_scattered = raw_calls_mutect2_vcf_out
        Array[File]? raw_calls_mutect2_vcf_idx_scattered = raw_calls_mutect2_vcf_idx_out
        Array[File]? raw_mutect2_stats_scattered = raw_mutect2_stats_out
        Array[File]? raw_mutect2_bam_out_scattered = raw_mutect2_bam_out_out
        Array[File]? raw_mutect2_bai_out_scattered = raw_mutect2_bai_out_out
        Array[File]? raw_mutect2_artifact_priors_scattered = raw_mutect2_artifact_priors_out
    }
}
