version development

# +-------------------------------------------------------------------------+
# | THIS FILE IS GENERATED BY CODE - DO NOT EDIT.                           |
# | Generated by wdl/codegen/generate.py from wdl/codegen/spec.py           |
# | To regenerate: python wdl/codegen/generate.py                           |
# +-------------------------------------------------------------------------+

import "shard.wdl" as sh
import "patient.wdl" as p

workflow UpdateShards {
    input {
        Patient patient
        Array[File]? raw_calls_mutect2_vcf_scattered
        Array[File]? raw_calls_mutect2_vcf_idx_scattered
        Array[File]? raw_mutect2_stats_scattered
        Array[File]? raw_mutect2_bam_out_scattered
        Array[File]? raw_mutect2_bai_out_scattered
        Array[File]? raw_mutect2_artifact_priors_scattered
    }

    # Overlay each scattered shard-output array onto patient.shards in a single pass;
    # an absent or empty array leaves the field unchanged.
    # INVARIANT: any provided array has length == length(patient.shards).
    Array[File] raw_calls_mutect2_vcf_scattered_arr = select_first([raw_calls_mutect2_vcf_scattered, []])
    Array[File] raw_calls_mutect2_vcf_idx_scattered_arr = select_first([raw_calls_mutect2_vcf_idx_scattered, []])
    Array[File] raw_mutect2_stats_scattered_arr = select_first([raw_mutect2_stats_scattered, []])
    Array[File] raw_mutect2_bam_out_scattered_arr = select_first([raw_mutect2_bam_out_scattered, []])
    Array[File] raw_mutect2_bai_out_scattered_arr = select_first([raw_mutect2_bai_out_scattered, []])
    Array[File] raw_mutect2_artifact_priors_scattered_arr = select_first([raw_mutect2_artifact_priors_scattered, []])

    scatter (i in range(length(patient.shards))) {
        Shard shard_i = patient.shards[i]
        Shard updated_shard_i = object {
            id: shard_i.id,
            intervals: shard_i.intervals,
            skip: shard_i.skip,
            is_high_mem: shard_i.is_high_mem,
            raw_calls_mutect2_vcf: if length(raw_calls_mutect2_vcf_scattered_arr) > 0 then raw_calls_mutect2_vcf_scattered_arr[i] else shard_i.raw_calls_mutect2_vcf,
            raw_calls_mutect2_vcf_idx: if length(raw_calls_mutect2_vcf_idx_scattered_arr) > 0 then raw_calls_mutect2_vcf_idx_scattered_arr[i] else shard_i.raw_calls_mutect2_vcf_idx,
            raw_mutect2_stats: if length(raw_mutect2_stats_scattered_arr) > 0 then raw_mutect2_stats_scattered_arr[i] else shard_i.raw_mutect2_stats,
            raw_mutect2_bam_out: if length(raw_mutect2_bam_out_scattered_arr) > 0 then raw_mutect2_bam_out_scattered_arr[i] else shard_i.raw_mutect2_bam_out,
            raw_mutect2_bai_out: if length(raw_mutect2_bai_out_scattered_arr) > 0 then raw_mutect2_bai_out_scattered_arr[i] else shard_i.raw_mutect2_bai_out,
            raw_mutect2_artifact_priors: if length(raw_mutect2_artifact_priors_scattered_arr) > 0 then raw_mutect2_artifact_priors_scattered_arr[i] else shard_i.raw_mutect2_artifact_priors
        }
    }
    Array[Shard] shards = updated_shard_i

    # Only shards change here; every other patient field is carried over.
    Patient updated_patient_obj = object {
        name: patient.name,
        sex: patient.sex,
        samples: patient.samples,
        tumor_samples: patient.tumor_samples,
        normal_samples: patient.normal_samples,
        has_tumor: patient.has_tumor,
        has_normal: patient.has_normal,
        matched_normal_sample: patient.matched_normal_sample,
        shards: shards,
        raw_snv_calls_vcf: patient.raw_snv_calls_vcf,
        raw_snv_calls_vcf_idx: patient.raw_snv_calls_vcf_idx,
        mutect2_stats: patient.mutect2_stats,
        orientation_bias: patient.orientation_bias,
        filtered_vcf: patient.filtered_vcf,
        filtered_vcf_idx: patient.filtered_vcf_idx,
        filtering_stats: patient.filtering_stats,
        mask_vcf: patient.mask_vcf,
        mask_vcf_idx: patient.mask_vcf_idx,
        mask_name: patient.mask_name,
        somatic_vcf: patient.somatic_vcf,
        somatic_vcf_idx: patient.somatic_vcf_idx,
        num_somatic_variants: patient.num_somatic_variants,
        germline_vcf: patient.germline_vcf,
        germline_vcf_idx: patient.germline_vcf_idx,
        num_germline_variants: patient.num_germline_variants,
        somatic_calls_bam: patient.somatic_calls_bam,
        somatic_calls_bai: patient.somatic_calls_bai,
        rare_germline_alleles: patient.rare_germline_alleles,
        rare_germline_alleles_idx: patient.rare_germline_alleles_idx,
        gvcf: patient.gvcf,
        gvcf_idx: patient.gvcf_idx,
        snp_ref_counts: patient.snp_ref_counts,
        snp_alt_counts: patient.snp_alt_counts,
        snp_other_alt_counts: patient.snp_other_alt_counts,
        snp_sample_correlation: patient.snp_sample_correlation,
        snp_sample_correlation_min: patient.snp_sample_correlation_min,
        modeled_segments: patient.modeled_segments,
        phylogic_sif_file: patient.phylogic_sif_file,
        phylogic_report: patient.phylogic_report,
        phylogic_ccfs_cnvs: patient.phylogic_ccfs_cnvs,
        phylogic_ccfs_snvs: patient.phylogic_ccfs_snvs,
        phylogic_constrained_ccf: patient.phylogic_constrained_ccf,
        phylogic_cluster_ccfs: patient.phylogic_cluster_ccfs,
        phylogic_build_tree_posteriors: patient.phylogic_build_tree_posteriors,
        phylogic_growth_rates: patient.phylogic_growth_rates,
        phylogic_growth_rate_plot: patient.phylogic_growth_rate_plot,
        phylogic_timing_report: patient.phylogic_timing_report,
        phylogic_timing_wgd_supporting_events: patient.phylogic_timing_wgd_supporting_events,
        phylogic_timing_graph: patient.phylogic_timing_graph,
        phylogic_timing_comparison: patient.phylogic_timing_comparison,
        phylogic_timing_table: patient.phylogic_timing_table
    }

    output {
        Patient updated_patient = updated_patient_obj
    }
}
