version development

# +-------------------------------------------------------------------------+
# | THIS FILE IS GENERATED BY CODE - DO NOT EDIT.                           |
# | Generated by wdl/codegen/generate.py from wdl/codegen/spec.py           |
# | To regenerate: python wdl/codegen/generate.py                           |
# +-------------------------------------------------------------------------+

import "patient.wdl" as p

workflow MergePatients {
    input {
        Patient patient
        Patient other
    }

    # Keep patient's identity (name + sample structure); overlay every result field
    # from `other` when it is defined, otherwise keep patient's value.
    Patient pat = object {
        name: patient.name,
        sex: if defined(other.sex) then other.sex else patient.sex,
        samples: patient.samples,
        tumor_samples: patient.tumor_samples,
        normal_samples: patient.normal_samples,
        has_tumor: patient.has_tumor,
        has_normal: patient.has_normal,
        matched_normal_sample: if defined(other.matched_normal_sample) then other.matched_normal_sample else patient.matched_normal_sample,
        shards: if defined(other.shards) then other.shards else patient.shards,
        raw_snv_calls_vcf: if defined(other.raw_snv_calls_vcf) then other.raw_snv_calls_vcf else patient.raw_snv_calls_vcf,
        raw_snv_calls_vcf_idx: if defined(other.raw_snv_calls_vcf_idx) then other.raw_snv_calls_vcf_idx else patient.raw_snv_calls_vcf_idx,
        mutect2_stats: if defined(other.mutect2_stats) then other.mutect2_stats else patient.mutect2_stats,
        orientation_bias: if defined(other.orientation_bias) then other.orientation_bias else patient.orientation_bias,
        filtered_vcf: if defined(other.filtered_vcf) then other.filtered_vcf else patient.filtered_vcf,
        filtered_vcf_idx: if defined(other.filtered_vcf_idx) then other.filtered_vcf_idx else patient.filtered_vcf_idx,
        filtering_stats: if defined(other.filtering_stats) then other.filtering_stats else patient.filtering_stats,
        mask_vcf: if defined(other.mask_vcf) then other.mask_vcf else patient.mask_vcf,
        mask_vcf_idx: if defined(other.mask_vcf_idx) then other.mask_vcf_idx else patient.mask_vcf_idx,
        mask_name: if defined(other.mask_name) then other.mask_name else patient.mask_name,
        somatic_vcf: if defined(other.somatic_vcf) then other.somatic_vcf else patient.somatic_vcf,
        somatic_vcf_idx: if defined(other.somatic_vcf_idx) then other.somatic_vcf_idx else patient.somatic_vcf_idx,
        num_somatic_variants: if defined(other.num_somatic_variants) then other.num_somatic_variants else patient.num_somatic_variants,
        germline_vcf: if defined(other.germline_vcf) then other.germline_vcf else patient.germline_vcf,
        germline_vcf_idx: if defined(other.germline_vcf_idx) then other.germline_vcf_idx else patient.germline_vcf_idx,
        num_germline_variants: if defined(other.num_germline_variants) then other.num_germline_variants else patient.num_germline_variants,
        somatic_calls_bam: if defined(other.somatic_calls_bam) then other.somatic_calls_bam else patient.somatic_calls_bam,
        somatic_calls_bai: if defined(other.somatic_calls_bai) then other.somatic_calls_bai else patient.somatic_calls_bai,
        rare_germline_alleles: if defined(other.rare_germline_alleles) then other.rare_germline_alleles else patient.rare_germline_alleles,
        rare_germline_alleles_idx: if defined(other.rare_germline_alleles_idx) then other.rare_germline_alleles_idx else patient.rare_germline_alleles_idx,
        gvcf: if defined(other.gvcf) then other.gvcf else patient.gvcf,
        gvcf_idx: if defined(other.gvcf_idx) then other.gvcf_idx else patient.gvcf_idx,
        snp_ref_counts: if defined(other.snp_ref_counts) then other.snp_ref_counts else patient.snp_ref_counts,
        snp_alt_counts: if defined(other.snp_alt_counts) then other.snp_alt_counts else patient.snp_alt_counts,
        snp_other_alt_counts: if defined(other.snp_other_alt_counts) then other.snp_other_alt_counts else patient.snp_other_alt_counts,
        snp_sample_correlation: if defined(other.snp_sample_correlation) then other.snp_sample_correlation else patient.snp_sample_correlation,
        snp_sample_correlation_min: if defined(other.snp_sample_correlation_min) then other.snp_sample_correlation_min else patient.snp_sample_correlation_min,
        modeled_segments: if defined(other.modeled_segments) then other.modeled_segments else patient.modeled_segments,
        phylogic_sif_file: if defined(other.phylogic_sif_file) then other.phylogic_sif_file else patient.phylogic_sif_file,
        phylogic_report: if defined(other.phylogic_report) then other.phylogic_report else patient.phylogic_report,
        phylogic_ccfs_cnvs: if defined(other.phylogic_ccfs_cnvs) then other.phylogic_ccfs_cnvs else patient.phylogic_ccfs_cnvs,
        phylogic_ccfs_snvs: if defined(other.phylogic_ccfs_snvs) then other.phylogic_ccfs_snvs else patient.phylogic_ccfs_snvs,
        phylogic_constrained_ccf: if defined(other.phylogic_constrained_ccf) then other.phylogic_constrained_ccf else patient.phylogic_constrained_ccf,
        phylogic_cluster_ccfs: if defined(other.phylogic_cluster_ccfs) then other.phylogic_cluster_ccfs else patient.phylogic_cluster_ccfs,
        phylogic_build_tree_posteriors: if defined(other.phylogic_build_tree_posteriors) then other.phylogic_build_tree_posteriors else patient.phylogic_build_tree_posteriors,
        phylogic_growth_rates: if defined(other.phylogic_growth_rates) then other.phylogic_growth_rates else patient.phylogic_growth_rates,
        phylogic_growth_rate_plot: if defined(other.phylogic_growth_rate_plot) then other.phylogic_growth_rate_plot else patient.phylogic_growth_rate_plot,
        phylogic_timing_report: if defined(other.phylogic_timing_report) then other.phylogic_timing_report else patient.phylogic_timing_report,
        phylogic_timing_wgd_supporting_events: if defined(other.phylogic_timing_wgd_supporting_events) then other.phylogic_timing_wgd_supporting_events else patient.phylogic_timing_wgd_supporting_events,
        phylogic_timing_graph: if defined(other.phylogic_timing_graph) then other.phylogic_timing_graph else patient.phylogic_timing_graph,
        phylogic_timing_comparison: if defined(other.phylogic_timing_comparison) then other.phylogic_timing_comparison else patient.phylogic_timing_comparison,
        phylogic_timing_table: if defined(other.phylogic_timing_table) then other.phylogic_timing_table else patient.phylogic_timing_table
    }

    output {
        Patient updated_patient = pat
    }
}
