version development

# +-------------------------------------------------------------------------+
# | THIS FILE IS GENERATED BY CODE - DO NOT EDIT.                           |
# | Generated by wdl/codegen/generate.py from wdl/codegen/spec.py         |
# | Generated at 2026:06:20:22:54:47                                      |
# | To regenerate: python wdl/codegen/generate.py                         |
# +-------------------------------------------------------------------------+

import "sequencing_run.wdl" as seqrun

struct Sample {
    String               name
    String               bam_name
    Array[SequencingRun] sequencing_runs
    Boolean              is_tumor
    File?                harmonized_callable_loci           # GATK CallableLoci | harmonization
    File?                harmonized_denoised_total_copy_ratios  # GATK DenoiseReadCounts | harmonization
    File?                harmonized_snppanel_allelic_pileup_summaries  # GATK GetPileupSummaries | harmonization
    File?                contamination_table                # GATK CalculateContamination
    File?                af_segmentation_table              # GATK CalculateContamination / ModelSegments
    File?                allelic_pileup_summaries           # snppanel + rare germline pileups
    File?                aggregated_allelic_read_counts     # PileupToAllelicCounts
    Float?               genotype_error_probabilities       # PileupToAllelicCounts
    File?                af_model_parameters                # GATK ModelSegments
    File?                cr_model_parameters                # GATK ModelSegments
    File?                called_copy_ratio_segmentation     # GATK CallCopyRatioSegments + merge
    File?                cr_plot                            # GATK PlotModeledSegments
    File?                acs_copy_ratio_segmentation        # ModelSegmentsToACSConversion
    Float?               acs_copy_ratio_skew                # ModelSegmentsToACSConversion
    File?                annotated_somatic_variants         # GATK Funcotator
    File?                annotated_somatic_variants_idx     # GATK Funcotator
    File?                absolute_snv_maf                   # ABSOLUTE input
    File?                absolute_indel_maf                 # ABSOLUTE input
    File?                absolute_acr_rdata                 # ABSOLUTE
    File?                absolute_acr_plot                  # ABSOLUTE
    Int?                 absolute_acr_solution              # manual
    File?                absolute_acr_maf                   # ABSOLUTE + Postprocess
    File?                absolute_acr_segtab                # ABSOLUTE + Postprocess
    File?                absolute_acr_segtab_igv            # ABSOLUTE + Postprocess
    File?                absolute_acr_table                 # ABSOLUTE
    Float?               absolute_acr_purity                # ABSOLUTE
    Float?               absolute_acr_ploidy                # ABSOLUTE
    File?                absolute_tcr_rdata                 # ABSOLUTE
    File?                absolute_tcr_plot                  # ABSOLUTE
    Int?                 absolute_tcr_solution              # manual
    File?                absolute_tcr_maf                   # ABSOLUTE + Postprocess
    File?                absolute_tcr_segtab                # ABSOLUTE + Postprocess
    File?                absolute_tcr_segtab_igv            # ABSOLUTE + Postprocess
    File?                absolute_tcr_table                 # ABSOLUTE
    Float?               absolute_tcr_purity                # ABSOLUTE
    Float?               absolute_tcr_ploidy                # ABSOLUTE
    Int?                 timepoint                          # manual
}

workflow UpdateSample {
    input {
        Sample sample
        String? name
        String? bam_name
        Array[SequencingRun]? sequencing_runs
        Boolean? is_tumor
        File? harmonized_callable_loci
        File? harmonized_denoised_total_copy_ratios
        File? harmonized_snppanel_allelic_pileup_summaries
        File? contamination_table
        File? af_segmentation_table
        File? allelic_pileup_summaries
        File? aggregated_allelic_read_counts
        Float? genotype_error_probabilities
        File? af_model_parameters
        File? cr_model_parameters
        File? called_copy_ratio_segmentation
        File? cr_plot
        File? acs_copy_ratio_segmentation
        Float? acs_copy_ratio_skew
        File? annotated_somatic_variants
        File? annotated_somatic_variants_idx
        File? absolute_snv_maf
        File? absolute_indel_maf
        File? absolute_acr_rdata
        File? absolute_acr_plot
        Int? absolute_acr_solution
        File? absolute_acr_maf
        File? absolute_acr_segtab
        File? absolute_acr_segtab_igv
        File? absolute_acr_table
        Float? absolute_acr_purity
        Float? absolute_acr_ploidy
        File? absolute_tcr_rdata
        File? absolute_tcr_plot
        Int? absolute_tcr_solution
        File? absolute_tcr_maf
        File? absolute_tcr_segtab
        File? absolute_tcr_segtab_igv
        File? absolute_tcr_table
        Float? absolute_tcr_purity
        Float? absolute_tcr_ploidy
        Int? timepoint
    }

    Sample updated = object {
        name: select_first([name, sample.name]),
        bam_name: select_first([bam_name, sample.bam_name]),
        sequencing_runs: select_first([sequencing_runs, sample.sequencing_runs]),
        is_tumor: select_first([is_tumor, sample.is_tumor]),
        harmonized_callable_loci: if defined(harmonized_callable_loci) then harmonized_callable_loci else sample.harmonized_callable_loci,
        harmonized_denoised_total_copy_ratios: if defined(harmonized_denoised_total_copy_ratios) then harmonized_denoised_total_copy_ratios else sample.harmonized_denoised_total_copy_ratios,
        harmonized_snppanel_allelic_pileup_summaries: if defined(harmonized_snppanel_allelic_pileup_summaries) then harmonized_snppanel_allelic_pileup_summaries else sample.harmonized_snppanel_allelic_pileup_summaries,
        contamination_table: if defined(contamination_table) then contamination_table else sample.contamination_table,
        af_segmentation_table: if defined(af_segmentation_table) then af_segmentation_table else sample.af_segmentation_table,
        allelic_pileup_summaries: if defined(allelic_pileup_summaries) then allelic_pileup_summaries else sample.allelic_pileup_summaries,
        aggregated_allelic_read_counts: if defined(aggregated_allelic_read_counts) then aggregated_allelic_read_counts else sample.aggregated_allelic_read_counts,
        genotype_error_probabilities: if defined(genotype_error_probabilities) then genotype_error_probabilities else sample.genotype_error_probabilities,
        af_model_parameters: if defined(af_model_parameters) then af_model_parameters else sample.af_model_parameters,
        cr_model_parameters: if defined(cr_model_parameters) then cr_model_parameters else sample.cr_model_parameters,
        called_copy_ratio_segmentation: if defined(called_copy_ratio_segmentation) then called_copy_ratio_segmentation else sample.called_copy_ratio_segmentation,
        cr_plot: if defined(cr_plot) then cr_plot else sample.cr_plot,
        acs_copy_ratio_segmentation: if defined(acs_copy_ratio_segmentation) then acs_copy_ratio_segmentation else sample.acs_copy_ratio_segmentation,
        acs_copy_ratio_skew: if defined(acs_copy_ratio_skew) then acs_copy_ratio_skew else sample.acs_copy_ratio_skew,
        annotated_somatic_variants: if defined(annotated_somatic_variants) then annotated_somatic_variants else sample.annotated_somatic_variants,
        annotated_somatic_variants_idx: if defined(annotated_somatic_variants_idx) then annotated_somatic_variants_idx else sample.annotated_somatic_variants_idx,
        absolute_snv_maf: if defined(absolute_snv_maf) then absolute_snv_maf else sample.absolute_snv_maf,
        absolute_indel_maf: if defined(absolute_indel_maf) then absolute_indel_maf else sample.absolute_indel_maf,
        absolute_acr_rdata: if defined(absolute_acr_rdata) then absolute_acr_rdata else sample.absolute_acr_rdata,
        absolute_acr_plot: if defined(absolute_acr_plot) then absolute_acr_plot else sample.absolute_acr_plot,
        absolute_acr_solution: if defined(absolute_acr_solution) then absolute_acr_solution else sample.absolute_acr_solution,
        absolute_acr_maf: if defined(absolute_acr_maf) then absolute_acr_maf else sample.absolute_acr_maf,
        absolute_acr_segtab: if defined(absolute_acr_segtab) then absolute_acr_segtab else sample.absolute_acr_segtab,
        absolute_acr_segtab_igv: if defined(absolute_acr_segtab_igv) then absolute_acr_segtab_igv else sample.absolute_acr_segtab_igv,
        absolute_acr_table: if defined(absolute_acr_table) then absolute_acr_table else sample.absolute_acr_table,
        absolute_acr_purity: if defined(absolute_acr_purity) then absolute_acr_purity else sample.absolute_acr_purity,
        absolute_acr_ploidy: if defined(absolute_acr_ploidy) then absolute_acr_ploidy else sample.absolute_acr_ploidy,
        absolute_tcr_rdata: if defined(absolute_tcr_rdata) then absolute_tcr_rdata else sample.absolute_tcr_rdata,
        absolute_tcr_plot: if defined(absolute_tcr_plot) then absolute_tcr_plot else sample.absolute_tcr_plot,
        absolute_tcr_solution: if defined(absolute_tcr_solution) then absolute_tcr_solution else sample.absolute_tcr_solution,
        absolute_tcr_maf: if defined(absolute_tcr_maf) then absolute_tcr_maf else sample.absolute_tcr_maf,
        absolute_tcr_segtab: if defined(absolute_tcr_segtab) then absolute_tcr_segtab else sample.absolute_tcr_segtab,
        absolute_tcr_segtab_igv: if defined(absolute_tcr_segtab_igv) then absolute_tcr_segtab_igv else sample.absolute_tcr_segtab_igv,
        absolute_tcr_table: if defined(absolute_tcr_table) then absolute_tcr_table else sample.absolute_tcr_table,
        absolute_tcr_purity: if defined(absolute_tcr_purity) then absolute_tcr_purity else sample.absolute_tcr_purity,
        absolute_tcr_ploidy: if defined(absolute_tcr_ploidy) then absolute_tcr_ploidy else sample.absolute_tcr_ploidy,
        timepoint: if defined(timepoint) then timepoint else sample.timepoint
    }

    output {
        Sample updated_sample = updated
    }
}
